= Getting Started (WIP/DRAFT Version)

How to set up the OP-TEE development environment for this project.

== Prerequisites

Although OP-TEE recommends using Ubuntu (22.04), for this project we prefer Debian 12 and have verified that our build works correctly on Debian 12.

== Setting up the OP-TEE Development Environment

The easiest way to setup an OP-TEE development environment is to check out the https://github.com/OP-TEE/build[OP-TEE/build] repository and follow the https://optee.readthedocs.io/en/latest/building/gits/build.html#[OP-TEE build instructions] that use the https://source.android.com/docs/setup/download[repo] command from the https://source.android.com/[AOSP] project. The instructions here are meant to supplement those instructions.

NOTE:: These instructions assume you have installed the Nix package manager to supplement Debian's built-in `apt-install`.  [A full Nix-based build would be nice, but is not in the current scope of this project.]

=== Installing necessary APT packages

. `./scripts/install-optee-prereqs.sh`

=== Installing Nix

See https://www.hillenius.net/post/debian-nix-ii/[Updated First Steps With Nix on Debian] for recommended instructions on installing Nix under Debian. You also need to add the following line to `/etc/nix/nix.conf`:

[source]
----
experimental-features = nix-command flakes
----

=== Installing Nix Packages

For now, we are assuming you are using `nix profile install`.

. `nix profile install nixpkgs#git-repo`  # To install the AOSP `repo` tool

=== Get the Source Code

Configure for QEMU v8.

If you haven't done it already:

```
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
```

then:

. `mkdir -p optee-qemu8`
. `cd optee-qemu8`
. `repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml`
. `repo sync`

=== Get the Toolchains

. `cd build`
. `make -j2 toolchains`


// This is not used anymore
// Read the message about "To get started you need Cargo's bin directory ... in your PATH environment variable" and run the command to set PATH

//. `. "$HOME/optee-qemu8/build/../toolchains/rust/.cargo/env"`

=== Build OP-TEE

. `make -j$(nproc) RUST_ENABLE=n check`

The `check` target will start QEMU and run tests.

NOTE:: `RUST_ENABLE=n` is a workaround for a build issue that occurs on ARM hosts. It is not needed on AMD64 systems and the current build sets `RUST_ENABLE` to `no` by default on ARM64.

=== Mounting shared dir inside QEMU







